/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'user1' at '16. 9. 26 오전 11:17' with Gradle 2.14.1
 *
 * @author user1, @date 16. 9. 26 오전 11:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
