/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'user1' at '16. 9. 6 오전 9:14' with Gradle 2.14.1
 *
 * @author user1, @date 16. 9. 6 오전 9:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
